version: "3"

services:

  next:
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ..:/namu:cached
      - ${SSH_KEY_PATH:-~/.ssh/id_rsa}:/root/.ssh/id_rsa:ro
    env_file:
      - .env.local
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:14
    restart: always
    tty: true
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  db-data:
