name: Build and Deploy

on:
  push:
    branches:
      - main  # Runs the action on push to the main branch


jobs:
  build:
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres:14
            env:
                POSTGRES_PASSWORD: secret
                POSTGRES_DB: namukilke
                POSTGRES_USER: namukilke
            options: >-
                --health-cmd pg_isready
                --health-interval 6s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 5432:5432

    steps:
    #   Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure
    #   - name: Azure Login
        # uses: azure/login@v1
        # with:
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the Azure Service Principal credentials stored in secrets
          
      # Login to ACR
    #   - name: Docker login to ACR
        # # uses: azure/docker-login@v1
        # with:
        # # #   login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        # #   username: ${{ secrets.REGISTRY_USERNAME }}
        #   password: ${{ secrets.REGISTRY_PASSWORD }}
            
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            driver-opts: |
                network=host
            cleanup: true

      # Build the docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
            context: .
            push: false
            # tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/vaalikoppi/vaalikoppi:${{ github.sha }}
            tags: namukilke:latest
            # There is intentionally no scope on the cache due to github's cache access restrictions.
            # Both the release and debug file will now be stored in the same location.
            # cache-from: type=gha 
            # cache-to: type=gha,mode=max 
            build-args: |
              "DATABASE_URL=postgres://namukilke:secret@localhost:5432/namukilke"
            allow: |
              network.host
              security.insecure
            network: host
      
      # Pust the image to ACR
    #   - name: Push image to ACR
        # run: |
        #   docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/vaaliplatta:latest

      # Deploy to Azure App Service
    #   - name: Deploy to Azure App Service
        # # uses: azure/webapps-deploy@v3
        # with:
        # # #   app-name: vaaliplatta  # Azure App Service name
        # #   slot-name: production  # Change this if you use a deployment slot
        #   images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/vaaliplatta:latest
      
      # Log out
    #   - name: Azure logout
        # run: |
        #   az logout